wifi.start()
wifi.mode(wifi.STATIONAP)
wifi.ap.config({ ssid = "Light-Strip", pwd = "12345678" })
-- wifi.sta.config("Mayfield-Wifi", "mayfield")
dofile("Bootstrap.lua")
dofile("LightStripServer.lua")
-- dofile("MotorServer.lua")
